config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'gmaps/index'
  get     'login', to: 'sessions#new'
  post    'login', to: 'sessions#create'
  get  'logout', to: 'sessions#destroy'
  delete  'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get 'contact', to: 'contacts#new'
  get 'portfolio', to: 'case_studies#index'
  get 'case-studies/hr'
  get 'industries/healthcare'
  get 'industries/retail'
  get 'industries/digital'
  get 'industries/logistics'
  get 'industries/travel'
  get 'industries/media'
  get 'skills', to: 'skills#index'
  get 'skills/laravel'
  get 'skills/codeigniter'
  get 'skills/symfony'
  get 'skills/ror'
  get 'skills/reactnative'
  get 'skills/reactjs'
  get 'skills/vuejs'
  get 'skills/android'
  get 'skills/nodejs'
  get 'skills/swift'
  get 'skills/ios'
  get 'skills/angularjs'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get '/application-development', to: 'static_pages#application_development'
  get '/application-maintenance', to: 'static_pages#application_maintenance'
  get '/application-modernization', to: 'static_pages#application_modernization'
  get '/testing-qa', to: 'static_pages#testing_qa'
  get '/co-development', to: 'static_pages#co_development'
  get '/dedicated-development-teams', to: 'static_pages#dedicated_development_teams'
  get '/geocoder4rails', to: 'gmaps#geocoder4rails'

  get '/twilios/send_test', to: 'twilios#send_test'
  post '/twilio-api/recv-sms', to: 'twilios#recv_sms'
  get '/twilio-api/recv-sms-test', to: 'twilios#recv_sms_test'

  get '/twilio-api', to: 'twilio_histories#iframe'
  get '/twilio_histories/:id/delete', to: 'twilio_histories#destroy'


  resources :microposts
  resources :users
  resources :contacts
  resources :gmaps
  resources :twilio_histories
  resources :messages
  resources :tracks
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:index, :new, :create, :edit, :update, :show]


  #root "static_pages#home"
  root "static_pages#home"
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  before_create :create_activation_digest

  attr_accessor :activation_token, :reset_token

  has_many :microposts

  # validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  validates :prefix, presence: true
  validates :number, presence: true

  def phone_number
    "1"+prefix+number.remove("-")
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end


  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        @user.send_activation_email
        flash[:info] = "Please check your email to activate your account."
        format.html { redirect_to root_url }
        #format.html { redirect_to login_path, notice: 'User was successfully created.' }
        #format.html { redirect_to @user, notice: 'User was successfully created.' }
        #format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :prefix, :number )
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<h1 class="text-center ">Signup Form</h1>

  <%= form_for(@user, url: signup_path,
             :html => {:autocomplete => "off", class:'mbr-form'}) do |f| %>

      <input type="email" style="display:none">
      <input type="password" style="display:none">

      <%= render 'shared/error_messages' %>

      <div class="form-group input-group-sm">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control ', :autocomplete => :off %>
      </div>
      <div class="form-group input-group-sm">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control ', :autocomplete => :off %>
      </div>
      <div class="form-group input-group-sm">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control ', :autocomplete => :off %>
      </div>

      <%
      options_prefix = {
          "": "",
          "850": "850",
          "970": "970"
      }
      options_number = {
          "": "",
          "270-1639": "270-1639",
          "366-4458": "366-4458"
      }
      %>

      <h4>Select a U.S. phone number</h4>
      <div class="col-sm-6 col-md-6 list-group float-left">
        <%= f.label :prefix, "Prefix" %>
        <%= f.select :prefix, options_for_select(options_prefix),{}, {class: 'form-control'} %>
      </div>
      <div class="col-sm-6 col-md-6 list-group float-right" style="padding-right: 0;">
        <%= f.label :number, "Phone number" %>
        <%= f.select :number, options_for_select(options_number),{}, {class: 'form-control'} %>
      </div>
      <div class="form-group"><p>&nbsp;</p></div>
      <div class="form-group list-group ">
        <%= f.submit "Create my account",
                     class: "btn btn-primary btn-sm float-left" %>
        <div class="float-right col-sm-5 col-md-5 ">
          Already signed up?
          <%=link_to "Log in", login_path, class: '' %>
        </div>
      </div>
      <div class="clearfix"></div>

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container-fluid">
  <p><br></p>
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <p id="notice"><%= notice %></p>

      <h1>Users</h1>

      <table class="table table-bordered">
        <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Activated</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.activated %></td>
            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New User', new_user_path %>

    </div>
  </div>

</div>

app/views/users/new.html.erb
<% provide(:title, "Signup") %>
<div class="mbr-fullscreen " style="background-color: white;">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <%= render 'form', user: @user %>

      </div>
    </div>

  </div>

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <p>
        <%= gravatar_for @user %>
        <strong>Name:</strong>
        <%= @user.name %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p>
    </section>
  </aside>
</div>