config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'gmaps/index'
  get     'login', to: 'sessions#new'
  post    'login', to: 'sessions#create'
  get  'logout', to: 'sessions#destroy'
  delete  'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get 'contact', to: 'contacts#new'
  get 'portfolio', to: 'case_studies#index'
  get 'case-studies/hr'
  get 'industries/healthcare'
  get 'industries/retail'
  get 'industries/digital'
  get 'industries/logistics'
  get 'industries/travel'
  get 'industries/media'
  get 'skills', to: 'skills#index'
  get 'skills/laravel'
  get 'skills/codeigniter'
  get 'skills/symfony'
  get 'skills/ror'
  get 'skills/reactnative'
  get 'skills/reactjs'
  get 'skills/vuejs'
  get 'skills/android'
  get 'skills/nodejs'
  get 'skills/swift'
  get 'skills/ios'
  get 'skills/angularjs'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get '/application-development', to: 'static_pages#application_development'
  get '/application-maintenance', to: 'static_pages#application_maintenance'
  get '/application-modernization', to: 'static_pages#application_modernization'
  get '/testing-qa', to: 'static_pages#testing_qa'
  get '/co-development', to: 'static_pages#co_development'
  get '/dedicated-development-teams', to: 'static_pages#dedicated_development_teams'
  get '/geocoder4rails', to: 'gmaps#geocoder4rails'

  get '/twilios/send_test', to: 'twilios#send_test'
  post '/twilio-api/recv-sms', to: 'twilios#recv_sms'
  get '/twilio-api/recv-sms-test', to: 'twilios#recv_sms_test'

  get '/twilio-api', to: 'twilio_histories#iframe'
  get '/twilio_histories/:id/delete', to: 'twilio_histories#destroy'


  resources :microposts
  resources :users
  resources :contacts
  resources :gmaps
  resources :twilio_histories
  resources :messages
  resources :tracks
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:index, :new, :create, :edit, :update, :show]


  #root "static_pages#home"
  root "static_pages#home"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>

  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<style>
  .header_new .menu_new li .sub_menu_new .hire_devl li a.ionic,
  .header_new .menu_new li .sub_menu_new .hire_devl li:hover a.ionic {
    background-position: 0 -2206px;
    border-bottom: 0 solid #d7d7d7;
  }

  .site-slogan {
    color: white;
    font-size: 20pt !important;
  }

  @media screen and (max-width: 1280px) {
    .site-slogan {
      font-size: 15pt !important;
    }
  }

  @media screen and (max-width: 1024px) {
    .site-slogan {
      font-size: 10pt !important;
    }
  }

  @media screen and (max-width: 765px) {
    .site-slogan {
      font-size: 10pt !important;
      line-height: 40px !important;
      display: block !important;
      /* float: left; */
      height: 40px !important;
      float: none!important;
    }
    .header_new .menu_new .hire_dvl_list{
      margin-left: 0px;
    }
    .header_new .menu_new li .sub_menu_new .sub-menu-list li a,
    .header_new .menu_new li .sub_menu_new .hire_devl li a{
      background-position-x: -10px!important;
    }
    .header_new .menu_new li .sub_menu_new .hire_devl li .laravel,
    .header_new .menu_new li .sub_menu_new .hire_devl li .ror
    {
      background-position-x: 7px!important;

    }
    .header_new .menu_new{
      left: 90px!important;
    }

    body {
      margin-top: 300px !important;
    }
  }

</style>
<script>

    $(function () {
        $(window).scroll(function () {
            if ($(this).scrollTop() > 500) {
                $('.logo img').attr('src', '/logo.png?v1');
            }
            if ($(this).scrollTop() < 500) {
                $('.logo img').attr('src', '/logo.png?v1');
            }
        });
    });

</script>
<header class="header_new navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-sm-3 col-lg-3 col-md-3">
        <a href="/" class="logo" title="WebMobile"><img src="/logo.png"
           width="100%" org-src="common/images/VC-Log-1.png?v1" alt="Dedicated - Logo"/></a>
        <span class="mob_icon2"></span>
      </div>
      <div class="col-xs-12 col-sm-9 col-lg-9 col-md-9">
        <span class="site-slogan" style="color: white;font-size: 20pt;line-height: 70px;
            float: left; height: 60px;">
          Wipying Jin's Portfolio Website
        </span>
        <nav>
          <ul class="nav navbar-nav navbar-right" style="margin-top: 18px;">
            <li><%=link_to 'Help', help_path %></li>
            <!--li><%=link_to 'About', about_path %></li-->
            <% unless logged_in2? %>
              <li><%=link_to 'Signup', signup_path %></li>
              <li><%=link_to 'Log in', login_path %></li>
            <% else %>
              <li><%=link_to 'Inbox', messages_path %></li>
              <li><%=link_to 'Log out', logout_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="shortcut icon" href="/assets/images/wipying-122x217.png" type="image/x-icon">

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <meta name="description" content="">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>



  <link rel="stylesheet" href="/assets/web/assets/mobirise-icons/mobirise-icons.css">
  <link rel="stylesheet" href="/assets/tether/tether.min.css">
  <!--link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap-grid.min.css">
  <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap-reboot.min.css"-->
  <link rel="stylesheet" href="/assets/dropdown/css/style.css">
  <link rel="stylesheet" href="/assets/animatecss/animate.min.css">
  <link rel="stylesheet" href="/assets/socicon/css/styles.css">
  <link rel="stylesheet" href="/assets/theme/css/style.css">
  <link rel="stylesheet" href="/assets/mobirise/css/mbr-additional.css" type="text/css">


</head>

<body>

<section class="menu cid-qTkzRZLJNu" once="menu" id="menu1-0">
  <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <div class="hamburger">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
    </button>
    <div class="menu-logo">
      <div class="navbar-brand" data-turbolinks="false">
                    <span class="navbar-logo">
                        <a href="/">
                             <img src="/assets/images/wipying-122x217.png" class="rounded"
                                  alt="Mobirise" title="" style="height: 3.8rem;">
                        </a>
                    </span>
        <span class="navbar-caption-wrap">
            <a class="navbar-caption text-white display-4" href="/">
                            Wipying Jin's Porfolio</a></span>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true"
        data-turbolinks="false">
        <li class="nav-item">
          <a class="nav-link link text-white display-4" href="#top">
            <span class="mbri-home mbr-iconfont mbr-iconfont-btn"></span>
            Home
            <br>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link link text-white display-4" href="/#header16-f">
            <span class="mbri-code mbr-iconfont mbr-iconfont-btn"></span>
            Experiences
            <br>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link link text-white dropdown-toggle display-4" href="#progress-bars1-8" data-toggle="dropdown-submenu" aria-expanded="false">
            <span class="mbri-like mbr-iconfont mbr-iconfont-btn"></span>Skills
          </a>
          <div class="dropdown-menu">
            <a class="text-white dropdown-item display-4" href="/#progress-bars1-h">Frameworks &amp;
              Tools</a>
            <a class="text-white dropdown-item display-4" href="/#progress-bars1-i">Programming</a>
            <a class="text-white dropdown-item display-4" href="/#progress-bars1-j">Server &amp;
              Networking</a>
            <a class="text-white dropdown-item display-4" href="/#progress-bars1-8">Professional
              Skills</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link link text-white display-4" href="/#counters5-m">
            <span class="mbri-add-submenu mbr-iconfont mbr-iconfont-btn"></span>API
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link link text-white display-4" href="/#form1-n">
            <span class="mbri-contact-form mbr-iconfont mbr-iconfont-btn"></span>Contact
            Me
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link link text-white dropdown-toggle display-4" href="/#counters5-m" data-toggle="dropdown-submenu" aria-expanded="false">
            <span class="mbri-users mbr-iconfont mbr-iconfont-btn"></span>
          </a>
          <div class="dropdown-menu" data-turbolinks="false">
            <% if logged_in2? %>
              <a class="text-white dropdown-item display-4" href="/#counters5-m">Profile</a>
              <a class="text-white dropdown-item display-4" href="/#counters5-m">Settings</a>
              <a class="text-white dropdown-item display-4" href="<%=logout_url %>">Logout</a>
            <% else %>
              <a class="text-white dropdown-item display-4" href="<%=login_url %>">Log in</a>
              <a class="text-white dropdown-item display-4" href="<%=signup_url %>">Register</a>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</section>

<%= yield %>

<section class="cid-qTkAaeaxX5 mbr-reveal" id="footer1-2">


  <div class="container">
    <div class="media-container-row content text-white">
      <div class="col-12 col-md-3">
        <div class="media-wrap">
          <a href="https://wipying-jin.herokuapp.com/">
            <img src="/assets/images/wipying-122x217.png" alt="Mobirise" title="" class=" img-thumbnail">
          </a>
        </div>
      </div>
      <div class="col-12 col-md-3 mbr-fonts-style display-7">
        <h5 class="pb-3">
          Address
        </h5>
        <p class="mbr-text">Chestnut Ridge, NY 10977<br>New York, United States</p>
      </div>
      <div class="col-12 col-md-3 mbr-fonts-style display-7">
        <h5 class="pb-3">
          Contacts
        </h5>
        <p class="mbr-text">
          Email: ray.pride84@gmail.com&nbsp;<br><br></p>
      </div>
      <div class="col-12 col-md-3 mbr-fonts-style display-7">
        <h5 class="pb-3">
          Links
        </h5>
        <p class="mbr-text"><a class="text-primary" href="https://wipying-jin.herokuapp.com">Portfolio Website</a><br><br>
        </p>
      </div>
    </div>
    <div class="footer-lower">
      <div class="media-container-row">
        <div class="col-sm-12">
          <hr>
        </div>
      </div>
      <div class="media-container-row mbr-white">
        <div class="col-sm-6 copyright">
          <p class="mbr-text mbr-fonts-style display-7">
            © Copyright 2019 - Home edition</p>
        </div>
        <div class="col-md-6">
          <div class="social-list align-right" data-turbolinks="false">
            <div class="soc-item">
              <a href="https://twitter.com/mobirise" target="_blank">
                <span class="socicon-twitter socicon mbr-iconfont mbr-iconfont-social"></span>
              </a>
            </div>
            <div class="soc-item">
              <a href="https://www.facebook.com/pages/Mobirise/1616226671953247" target="_blank">
                <span class="socicon-facebook socicon mbr-iconfont mbr-iconfont-social"></span>
              </a>
            </div>
            <div class="soc-item">
              <a href="https://www.youtube.com/c/mobirise" target="_blank">
                <span class="socicon-youtube socicon mbr-iconfont mbr-iconfont-social"></span>
              </a>
            </div>
            <div class="soc-item">
              <a href="https://instagram.com/mobirise" target="_blank">
                <span class="socicon-instagram socicon mbr-iconfont mbr-iconfont-social"></span>
              </a>
            </div>
            <div class="soc-item">
              <a href="https://plus.google.com/u/0/+Mobirise" target="_blank">
                <span class="socicon-googleplus socicon mbr-iconfont mbr-iconfont-social"></span>
              </a>
            </div>
            <div class="soc-item">
              <a href="https://www.behance.net/Mobirise" target="_blank">
                <span class="socicon-behance socicon mbr-iconfont mbr-iconfont-social"></span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<script src="/assets/popper/popper.min.js"></script>
<script src="/assets/tether/tether.min.js"></script>
<script src="/assets/smoothscroll/smooth-scroll.js"></script>
<script src="/assets/dropdown/js/script.min.js"></script>
<script src="/assets/touchswipe/jquery.touch-swipe.min.js"></script>
<script src="/assets/viewportchecker/jquery.viewportchecker.js"></script>
<script src="/assets/parallax/jarallax.min.js"></script>
<script src="/assets/theme/js/script.js"></script>
<script src="/assets/formoid/formoid.min.js"></script>

<div id="scrollToTop" class="scrollToTop mbr-arrow-up">
  <a style="text-align: center;"><i class="mbr-arrow-up-icon mbr-arrow-up-icon-cm cm-icon cm-icon-smallarrow-up" )></i></a>
</div>
<input name="animation" type="hidden">

</body>
</html>